### ISSUE TITLE
Feature request: annotations for pods launched by containerproxy

### ISSUE THREAD

**Issue by lukeplausin** [openanalytics/containerproxy#25]
duplicate of https://github.com/openanalytics/shinyproxy/issues/152

I would like to add annotations to kubernetes pods launched by container proxy.

My use case is attaching an IAM role to containers with `kube2iam`. I am sure it would be useful for other things too.

**Comment by LEDfan** [comment]
Hi @Tazovsky

In order to not have to implement every Kubernetes feature in ContainerProxy, we decided to add a generic way of adding Kubernetes specific configuration to a ContainerProxy app. This feature is called `kubernetes-pod-patches` and allows to *patch* the specification of the Pod before it is created by ContainerProxy.
More information about this feature can be found [here](https://shinyproxy.io/documentation/configuration/#apps) (you have to scroll down a bit).
This should cover your use-case (both annotation and tolerations). Feel free to open an issue if you experience any issue with this feature.
The change is included in the just released [ShinyProxy 2.4.0](https://shinyproxy.io/downloads/#240)
