### ISSUE TITLE
Add link between user and containers to session

### ISSUE THREAD

**Issue by nysthee** [openanalytics/containerproxy#26]
Hey,

Is there a possibility to maintain state of  mapping between users and containers outside of the application? As an application restart seems to leave zombie containers running.

**Comment by fmannhardt** [comment]
Keeping the session on some kind of external store like REDIS or so would also be very useful for scaling since that would make containerproxy really stateless.

**Comment by LEDfan** [comment]
Hi

Since ShinyProxy 2.6.0 we have the [App Recovery feature](https://shinyproxy.io/documentation/app-recovery/) allowing you to restart ShinyProxy without loosing all active apps.

In ShinyProxy 3.0.0 (which we released today) you are now able to [store the session in Redis](https://shinyproxy.io/documentation/configuration/#session-and-app-persistence), on Kubernetes (and Docker Swarm) this allows you to run ShinyProxy in a High Available way, using multiple replicas, please have a look at the https://github.com/openanalytics/shinyproxy-operator for this.
