### ISSUE TITLE
Support request for Kubernetes PersistentVolumeClaims

### ISSUE THREAD

**Issue by insatomcat** [openanalytics/containerproxy#5]
Hello,

I looked at the code and it seems that containerproxy currently only supports kubernetes hostPath volumes.
Given that fabric8 seems to support PersistentVolumeClaims, I feel it might be a good idea to make containerproxy support them.
Indeed,  hostPath volumes are not recommended in a production environnement (you never know on which host the pods are going to be running + the data mounted may be used by other applications) : 
_"In a production cluster, you would not use hostPath. Instead a cluster administrator would provision a network resource like a Google Compute Engine persistent disk, an NFS share, or an Amazon Elastic Block Store volume."_ (https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)

Thank you.

**Comment by insatomcat** [comment]
PR #6 as a PoC that it should be pretty straightforward.

**Comment by tverbeke** [comment]
Thanks, @insatomcat. Fully agreed!

**Comment by LEDfan** [comment]
Hi @insatomcat

In order to not have to implement every Kubernetes feature in ContainerProxy, we decided to add a generic way of adding Kubernetes specific configuration to a ContainerProxy app. This feature is called `kubernetes-pod-patches` and allows to *patch* the specification of the Pod before it is created by ContainerProxy.
More information about this feature can be found [here](https://shinyproxy.io/documentation/configuration/#apps) (you have to scroll down a bit).
This should cover your use-case. Feel free to open an issue if you experience any issue with this feature.
The change is included in the just [ShinyProxy 2.4.0](https://shinyproxy.io/downloads/#240)
