### ISSUE TITLE
transparent upgrades

### ISSUE THREAD

**Issue by kfox1111** [openanalytics/containerproxy#55]
It would be great if upgrading containerproxy/shinyproxy didn't destroy all running apps but instead adopted the running sessions of the previous instance.

**Comment by LEDfan** [comment]
Hi @kfox1111 

This is something we are working on for the next release. On startup ShinyProxy checks for existing Docker containers (or Kubernetes pods) and using the [labels/annotations](https://shinyproxy.io/documentation/configuration/#app-container-labels-and-annotations) it discovers the existing apps. However, the current implementation will not restore existing apps if the configuration (i.e. application.yml) of ShinyProxy has changed. The purpose of this is to no restore apps when the configuration of such an app has changed (e.g. changing the port configuration may make the app broken). 

Maybe it's a good idea to only check whether the configuration of an app has changed, instead of the full shinyproxy configuration. This would allow to e.g. change the title of ShinyProxy.

**Comment by kfox1111** [comment]
Thats a step in the right direction. It solves the issue of needing to upgrade shinyproxy itself or take the node that its running on offline.

But, K8s usually enables rapid application upgrades to fix issues / add features. Currently shinyproxy is limiting what can be done though because reconfiguration would break existing sessions. So ops folks are reluctant to apply dev's changes to production for applications. I think the most ideal situation would be for it to keep existing pods running and new application configuration changes would only apply to newly launched containers. This would allow existing sessions to continue to work If a user started an old version then it continuing to not have the new features would be expected behavior. If they want to get to the new version faster, they can just logout. Or the app would eventually timeout and get removed. Then the new version would kick in as soon as they go back in. Then any changes to a production environment can be made safely at any time allowing much more rapid development / release cycles.

Other changes to an application that can be important to production would be the ability to adjust the kubernetes pod spec for example, memory allocation. It may be that after running for a short time in production you discover a particular application may need more memory allocated as its ooming. Tweaking up a particular apps memory limits shouldn't require all existing app instances to break. It puts the ops folks in a bad spot of not applying a fix for one app to prevent breaking another app.

You mentioned using labels/annotations to discover the pods and reestablish connections. Could that pattern be extended to store the port number that the pod was launched with? Then a port change in the app spec wouldn't break the older apps. Connection would always use the port the pod was launched with, not the port currently configured in the app spec. Maybe this pattern could be used to store any such configuration items that would break connection reestablishment?

**Comment by LEDfan** [comment]
What you describe is the exact purpose of the ShinyProxy operator. It even goes one step further: the operator will never *restart* a ShinyProxy server, simply because this would break the (websocket) connection between the users browser and the Shiny apps. Such an restart would also cause some downtime. This also means that there is no recovery of existing apps needed. Instead of restarting a ShinyProxy server to apply new configuration, the operator creates an new (additional) ShinyProxy server. Any user that isn't currently using that old server is routed to the new server. Similarly, users which currently have a Shiny app running, are kept on the old server. Eventually, when nobody is using the old server, the operator removes the old server. 

>  If they want to get to the new version faster, they can just logout

With the operator, a message is shown to users on the old server, which includes a button to force the usage to the new server:

![image](https://user-images.githubusercontent.com/2996275/114511555-5bf7cc00-9c38-11eb-9bca-f3894bd7dbdc.png)

(implementing the same behavior when the user logs out is on our roadmap).

Some more information on the purpose of the operator can be found here: https://shinyproxy.io/documentation/deployment/#why-1
Note: we plan to write some more documentation on the behavior of the operator, since the above purpose may not be fully clear currently.

**Comment by kfox1111** [comment]
So are you launching a new shinyproxy, deleting the old one and having a shutdown hook that blocks until all the old users are off of it?

I guess this could be solved completely at the k8s level with such a solution. Interesting...

**Comment by LEDfan** [comment]
The old ShinyProxy server is deleted by the operator itself, not by some Kuberentes hooks/tools. This has a few reasons:
 - when the old ShinyProxy server is removed, some other resources need to be cleaned up as well (ConfigMap, Ingress). Especially for Ingress it's important that the operator has control over it.
 - we try to have the ShinyProxy itself as "operator independent" as possible. That means we don't want to add (too many) code to ShinyProxy itself, in order to make it compatible with the operator. This is not 100% possible, but we try to strive to this.
 - we have some plans for different kinds of "termination policies". For example, we could add an option to immediately kill the old ShinyProxy server, even if users are still using it. I think it makes sense to have all this logic in one place, therefore in the operator.

I hope this makes sense too you as well. Additional feedback is welcome of course!

**Comment by kfox1111** [comment]
Hmm.... That does make sense. But I can see one case that may not be handled by the operator, but maybe its considered a different issue. Say as a cluster-admin I'm trying to upgrade all of the compute nodes. I drain a node that shinyproxy is on. It would be nice if that drain didn't break working apps. k8s would issue the pod termination in that case, so a prestop hook might still be needed in that case.

**Comment by LEDfan** [comment]
The App Recovery feature is now part of [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10).

You can find more documentation on the new docs page: https://shinyproxy.io/documentation/app-recovery/ . Note that I included an option to recover apps even if the configuration of ShinyProxy has changed.
We are also releasing version 1.0.0 of the Operator today, which solves a similar problem.

Thank you for your feedback! Looking forward to any feedback you have on this feature.
